### ISSUE TITLE
Fails to load when output paths have been overridden in Brocfile

### ISSUE THREAD

**Issue by raido** [sglanzer/ember-cli-blanket#65] opened 2015-05-25 12:02 UTC
Continuing discussion from #60 

Fresh install worked fine for me too. But for my current project it fails. Null check does not fix it, then you would end up with moduleLoaderFinish is not defined error in end of the test run.

Edit: I figured out what is causing it to fail:

I have overriden outputPaths in the Brocfile:

```
outputPaths: {
        app: {
            css: {
                'app': '/assets/app.css'
            },
            js: '/assets/app.js'
        }
    }
```

This needs to be made compatible with overridden paths.

**Comment by raido** [comment] 2015-05-25 12:19
I investigated this a bit more, because outputPaths are overridden, the blueprint generation does not find the <script> tag for the "appname.js" from tests/index.html, thus does not append "blanket-options.js" and "blanket-loader.js" to the file and failing to run.

Installations successfully adds <style> tag but <script> tags are not added, thus running blueprint generation makes it work.

**Comment by avdv** [comment] 2015-05-29 07:01
I also faced this problem. Duplicate of #52

**Comment by mheisig** [comment] 2015-07-23 17:11
Isn't this how the rest of Ember CLI works? If you added custom outputPaths to your Brocfile you would have to make the corresponding path updates to the project index.html

**Comment by avdv** [comment] 2015-07-24 06:11
> If you added custom outputPaths to your Brocfile you would have to make the corresponding path updates to the project index.html

Yes, of course. And that's what we did.

But the point is, after changing the location of a file and then trying to install an addon, the addon should be able to find the file - because it should examine the Ember-CLI specific output path setting and not simply hard-code the name or location of the file.

What good is a setting if you cannot ever change it because everything breaks afterward?!

**Comment by sglanzer** [comment] 2015-07-24 11:22
Sorry for the frustration, but I have very limited time to work on this project currently.  If you want to submit a pull request, it seems like you already have most of the details necessary for the fix and I'd be happy to merge it.

**Comment by mheisig** [comment] 2015-07-24 15:41
>What good is a setting if you cannot ever change it because everything breaks afterward?!

Maybe I'm missing something in Ember CLI generally, but if you change the outputPath in the Brocfile, don't you have to manually update the app/index.html with the new paths? In other words, this add-on isn't doing anything different than what Ember CLI does from what I can tell.

I agree it would be great to have the asset paths be dynamic in all cases, but after poking around a bit I'm not sure how to make it happen. I can't figure out how to access the app properties (outputPaths) set in the Brocfile from within the blueprint that modifies the tests/index.html

**Closed** 2018-10-11 19:59 UTC
