### ISSUE TITLE
Utility classes (off the standard ember path) aren't being instrumented

### ISSUE THREAD

**Issue by sglanzer** [sglanzer/ember-cli-blanket#18] opened 2015-02-02 18:49 UTC

**Comment by djmitchella** [comment] 2015-02-10 20:54
I am literally in the middle of making a repro for this and went to make a new issue; I have a helper object in app/utils/..., and it doesn't get shown as covered. Ember-cli does suggest that 'utils' is the right place under http://www.ember-cli.com/#using-modules, but it doesn't seem to help. Moving it under 'helpers' doesn't make any difference, either. 

Weirdly, even if I put my helper class under /controllers, it _still_ doesn't register as being covered. It's just some bare utility functions, roughly like:

(app/utils/my-utils.js)
export default {
  helper1: function() { return "foo"; }
}

and I have a test that does

import myUtils from 'app/utils/my-utils';
module("myUtils tests");
test('helper works', function() {
  equal(myUtils.helper1(), "foo"); 
});

but that doesn't get shown as covered; I'm wondering if the issue is that it's not part of the Ember object hierarchy, rather than it being in an unexpected path. 

(I also have some global code in my real helper file that's outside the 'export default', and that doesn't show as covered either, for what it's worth)

**Comment by topaxi** [comment] 2015-03-01 14:21
None of my app/utils are reported as covered too, are there any workarounds or fixes?

**Comment by sglanzer** [comment] 2015-03-01 14:46
@topaxi Not currently.  The project instruments (wraps classes with JavaScript that monitors the lines executed)  any class included in the requirejs.entries loaded by ember-cli.  Unfortunately, this doesn't include anything that isn't in the standard trees ember-cli monitors.

The only solution I've thought of currently is to walk the full app tree and include any files not already in the requirejs.entries; however, I haven't had time to test this idea.  It's definitely on my todo list, but it will probably be a few weeks before it reaches the top of my priorities.

**Comment by huafu** [comment] 2015-03-11 02:32
I have the same issue here, but looks like it is just `initializers` and `utils`, included in the ember cli tree, which are shown in coverage, but reported as **not** covered. Tho they are all in `require.entries` (I removed irrelevant entries there to make it smaller):

```js
JSON.stringify(
  Ember.keys(require.entries).filter(function (entry) {
    return /\/(utils|initializers)\//.test(entry);
  })
)
```
```json
"[
  "wonder-app/initializers/contact-book-service",
  "wonder-app/initializers/cordova-service",
  "wonder-app/initializers/inject-notifier",
  "wonder-app/initializers/qna-service",
  "wonder-app/initializers/session-service",
  "wonder-app/utils/browser/uuid",
  "wonder-app/utils/computed/fmt",
  "wonder-app/utils/dial-prefix-for-country",
  "wonder-app/utils/is-coercible-number",
  "wonder-app/utils/parse-phone",
  "wonder-app/utils/qna/actions",
  "wonder-app/utils/qna/hooks",
  "wonder-app/utils/string-to-map",
  "wonder-app/utils/view/is-dom-accessible"
]"
```

Then they all appear in the coverage report, but appears as not covered, tho they're all or almost called, even have some tests for most of them so for sure they're called ;-)

**Comment by sglanzer** [comment] 2015-03-11 04:54
That's interesting, I guess I just assumed they weren't in the requirejs entries.  I haven't had a report of them showing up in coverage before, maybe CLI changed.  Not sure why they would be uncovered if they got instrumented, but it definitely gets us closer.

**Comment by djmitchella** [comment] 2015-03-11 13:35
Ah, to clarify, I'm seeing the same thing; when I said "[my helper object] doesn't get shown as covered", I meant "shows up in the report but with all lines not showing as covered". But as I said, I don't think it's related to paths, I think it's related to how they get loaded, because non-"Controller" objects in /controllers don't get shown as being covered even when they are.

**Comment by huafu** [comment] 2015-03-12 02:48
Yup, I guess EmberCLI loader does the `container.register(...)` before this addon's instrument them. So it's just a matter of where to make the call which is instrumenting the `require.entries` items.

**Comment by jschilli** [comment] 2015-03-12 03:16
might be worth looking app-boot.js (https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/app-boot.js).

The addon could return contentFor(‘app-boot’) to hop in early in the process.

It’s on my list to experiment with this hook - but it definitely is before the app boots.

**Comment by jschilli** [comment] 2015-03-19 19:35
I was opening a new issue to report the same but I'll add my comments here.

The issue is not that the other assets are not in the requirejs entries but rather that in the process of adding coverage to a file blanket ends up requiring the other dependencies before they themselves have been covered.

I've confirmed this by setting breakpoints in the 'imported' file and indeed it is in uncovered code

to @huafu's comment - I believe we're hooking in early enough - the reason I ended up down this rat hole was chasing something imported into an initializer

I'm thinking about options here - if blanket greedily consumes imports then we need to be able to override require 

Other options (radical) include annotating the code as a `postProcess` step in the addon

open to discussion

**Comment by jschilli** [comment] 2015-03-20 13:31
I've put up a branch testing out the concept of monkey-patching require

Before Coverage:
![std-blanket-coverage](https://cloud.githubusercontent.com/assets/122509/6752309/b3ee1fc8-cee3-11e4-9231-7c5027eb48a6.png)

After Coverage:
![update-blanket-coverage](https://cloud.githubusercontent.com/assets/122509/6752314/bc427804-cee3-11e4-8287-1f8a883af398.png)

The uncovered code in stock ember-cli-blanket is utils/util.js - it is imported from a 'covered' file.

pro-forma branch is up at: https://github.com/jschilli/ember-cli-blanket/tree/stub-require

all of the changes are isolated in: https://github.com/jschilli/ember-cli-blanket/blob/stub-require/lib/blanket-loader.js

@huafu - I was able to verify that with the require approach we can hook in early enough to capture initializers so we have that going for us

I'd like to get feedback on the approach of hijacking require.

Another alternative I'm thinking about is continuing with the original approach of navigating through requirejs.entries but pre-processing dependencies before letting blanket do its thing.  I think it will work but it's more code and we then have to deal with cycles etc

thoughts?

**Comment by Coobaha** [comment] 2015-03-20 14:06
I have `app/mixins` not covered also

**Comment by jschilli** [comment] 2015-03-20 14:09
@Coobaha 

npm i "git://github.com/jschilli/ember-cli-blanket.git#stub-require" and give it a whirl - I haven't tried mixins specifically but believe it should be covered

**Comment by Coobaha** [comment] 2015-03-20 14:15
@jschilli 

your branch shows 100% coverage for file, but I have no tests for it :)

**Comment by jschilli** [comment] 2015-03-20 14:19
@Coobaha not enough info to help - imported file? public repo? blanket will cover the lines if they are executed - regardless of who calls them

**Comment by Coobaha** [comment] 2015-03-20 14:31
Sorry, you are right @jschilli . After isolating coverage worked as it should - all ok :+1:

**Comment by sglanzer** [comment] 2015-03-25 03:27
I believe the latest commit from @jschilli addresses this issue.  Any modules imported into a module on the standard path will be included in the coverage.

This should address modules such as mixins, utility function modules or object models.

Version 0.3.3 has been released with these changes, I'll leave this issue open for a few days to gather feedback, but the early tests I've run with Jeff's change set look good.

**Comment by sglanzer** [comment] 2015-03-25 03:30
Note that modules that aren't imported won't be covered still, but I believe this should be addressed with an appropriately scoped issue and will likely require a rewrite using the postProcess hook.  It's also much less of priority in my opinion.

**Comment by jschilli** [comment] 2015-03-25 16:40
@sglanzer are there specific examples that aren't covered? that would be meaningful?  initializers? 

My question is if a module is not imported is it ever executed? unless that's the point - you want to report 0% coverage on modules in requirejs.entries that are never executed.  I have some ideas on that

**Comment by jschilli** [comment] 2015-03-26 16:30
I'll self reply here - I added blanket back to my main app and now very clearly see the issue with not covering requirejs.entries.

we're only covering files that are required - it's pretty important to reflect those files that aren't covered at all.

I'll take a swing @ this - may be a few days

**Closed** 2015-03-27 23:53 UTC
Labels: bug

**Comment by sglanzer** [comment] 2015-03-28 00:02
You rule Jeff =)
