### ISSUE TITLE
Problem with global vars in instrumented code: "ReferenceError: Webapp is not defined"

### ISSUE THREAD

**Issue by tschoartschi** [sglanzer/ember-cli-blanket#15] opened 2015-01-08 14:45 UTC
Hey!

I'm trying to integrate Blanket.js into our development workflow. I used ember-cli to scaffold the app. After that I tried to install ember-cli-blanket. But now our test suite doesn't work anymore. This is because we need to put a global variable onto the "window" scope (for communication with legacy code). Therefore our app.js file looks as follows:
```javascript
import Ember from 'ember';
import Resolver from 'ember/resolver';
import loadInitializers from 'ember/load-initializers';
import config from './config/environment';
Ember.MODEL_FACTORY_INJECTIONS = true;
var App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix, // NOT USED NOW, BUT NEEDED
  Resolver: Resolver
});
loadInitializers(App, config.modulePrefix);
var classifiedName = Ember.String.classify(config.modulePrefix);
// <-- HERE WE PUT APP CONFIG TO THE WINDOW SCOPE
if (config.exportApplicationGlobal) {
  window[classifiedName] = config.APP;
}
export default App;
```
For some reason the instrumented code doesn't work and throws the following error:
```javascript
"Uncaught Error: Error parsing instrumented code: ReferenceError: Webapp is not defined"
```
Without Blanket.js everything worked like a charm, so I wonder if we have to adjust our code or if there is a way to make it work with Blanket.js

Thanks for every hint and also for your work on ember-cli-blanket

**Comment by sglanzer** [comment] 2015-01-08 17:27
@tschoartschi Hey, I'm not sure if the issue is with the global variable or something else.  I tested

````
loadInitializers(App, config.modulePrefix);

window['MyTest'] = config.APP;
````

with the coverage turn on in an application I've been working on (200+ unit tests) and it executed without issue.

I'm running ember-cli 0.1.5 and ember 1.9.1 for reference.  Have you tested the theory with a fresh ember-cli project with the only addition being ember-cli-blanket and the global window variable?

**Comment by tschoartschi** [comment] 2015-01-09 14:37
Okay thanks for the pointer! I just tried it out and realized, that the config.APP was never put on the window. Then I browsed through our code and realized that someone put window.Webapp = {} into some test. Maybe this is the reason why it worked without instrumentation. 

Now I put the following code into the resolver.js (tests/helpers/resolver.js)
```javascript
import Ember from 'ember';
import Resolver from 'ember/resolver';
import config from '../../config/environment';

var resolver = Resolver.create();

resolver.namespace = {
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix
};

var classifiedName = Ember.String.classify(config.modulePrefix);
if (config.exportApplicationGlobal) {
    window[classifiedName] = config.APP;
}

export default resolver;
```
Don't know if this is the right place. I'm just starting to learn Ember and all the stuff around. Now the next error comes up:
```javascript
"Uncaught Error: Error parsing instrumented code: Error: Assertion Failed: The initializer 'simple-auth' has already been registered"
```
As you can see, we are using ember-cli-simple-auth. These kinds of errors are really hard to debug for a beginner like me :/ Any idea whats going on or were to start debugging?

**Comment by sglanzer** [comment] 2015-01-09 16:16
Yep, it's a known issue - the instrumentation loads all of the modules, so initializers that can only be loaded once need to be explicitly excluded for now.  This is the more detailed discussion with an example workaround https://github.com/sglanzer/ember-cli-blanket/issues/8

**Comment by sglanzer** [comment] 2015-01-30 17:21
Closing as a duplicate of #8

**Closed by sglanzer** 2015-01-30 17:21 UTC
