### ISSUE TITLE
`ember test` hangs without running tests

### ISSUE THREAD

**Issue by ryanlabouve** [sglanzer/ember-cli-blanket#60] opened 2015-05-15 22:40 UTC
Steps to reproduce:

`ember new testapp && cd testapp`
`ember install ember-cli-blanket`
`ember test`

Then it will hang without running any tests:
![terminal_ _phantomjs_ _85x52_and_new_issue_ _sglanzer_ember-cli-blanket_and_slack_and_dashboard_ _develop__222_commits_](https://cloud.githubusercontent.com/assets/1318878/7662968/d8fae820-fb28-11e4-9ae6-ad2a45462e34.jpg)

I'm on OSX.

"ember-cli-blanket": "0.5.1"

Here's my `ember -v`:
version: 0.2.4
node: 0.12.2
npm: 2.9.1

I love this project and I'm happy to help if there's anything I can do, but this may be a little over my head.

**Comment by jkatsnelson** [comment] 2015-05-15 22:52
I will second this.

I just upgraded an app to ember-cli 0.2.5. Tests are frozen because of blanket. Let me know when its patched so I can add blanket back to my project :-D

**Comment by jschilli** [comment] 2015-05-16 00:24
Would be helpful to know if blanket is running in the browser and only failing in ci mode.

**Comment by ryanlabouve** [comment] 2015-05-16 00:41
Not running in browser either. It has like, the window preview box and that's it. Screenshot attached.

![testapp_tests](https://cloud.githubusercontent.com/assets/1318878/7663949/49a0f6da-fb3a-11e4-9ec1-9c23bdadbc3f.jpg)

**Comment by jschilli** [comment] 2015-05-16 03:38
@sglanzer looks like qunit autostart toggle issue - must have been a flip-flop in the new release.


in the browser if I run `Qunit.start()` it starts and runs

not sure where that toggle is taking place.

I'll check mocha over the weekend

**Comment by jschilli** [comment] 2015-05-16 03:53
I upgraded one of my ember-cli-mocha projects to ember-cli 0.2.5 and all is fine. so this issue is isolated to qunit

**Comment by elwayman02** [comment] 2015-05-16 05:33
Yea, I can confirm that 0.2.5 is broken with qunit...same behavior that @jschilli described, can bypass in the browser to run it.

**Comment by elskwid** [comment] 2015-05-17 19:42
Adding my voice, this is indeed an issue, my temporary workaround was to force the autostart to true in `tests/index.html` like this:

```html
  <body>

    {{content-for 'body'}}
    {{content-for 'test-body'}}
    <script src="assets/vendor.js"></script>
    <script src="assets/test-support.js"></script>
    <script>
     /*
      * Force QUnit autostart to be true to work around changes in
      * ember-cli-qunit and ember-cli-blanket.
      *
      * Reference:
      * https://github.com/sglanzer/ember-cli-blanket/issues/60
      * https://github.com/ember-cli/ember-cli-qunit/commit/98c8d370d574adc4deb2ab438edd0d248b22155b
      */
      QUnit.config.autostart = true;
    </script>
    <script src="assets/app.js"></script>
    <script src="assets/blanket-options.js"></script>
    <script src="assets/blanket-loader.js"></script>
    <script src="testem.js"></script>
    <script src="assets/test-loader.js"></script>

    {{content-for 'body-footer'}}
    {{content-for 'test-body-footer'}}
  </body>

```

The two links in the reference show where there's some conflict with how the autostart is preserved. Since ember-cli-qunit defaults to true but this isn't reset until that timeout happens I feel like there's a timing issue. A quick check shows that ember-cli-blanket sees the autostart set to false in `blanket-require.js` and so it's set to false in `start.js` and so our tests don't start.

**Comment by DenizOkcu** [comment] 2015-05-18 11:51
Thanks @elskwid for the workaround.

this commit breaks it for me:
https://github.com/ember-cli/ember-cli-qunit/commit/98c8d370d574adc4deb2ab438edd0d248b22155b

In the comments:
> ...Important is, that ember-cli-addon developers respect this option as well and they don't override it directly like ember-cli-blanket was (debugging the reason why it suddenly stopped running tests take some time)...
>
> -- <cite>@vire</cite>

**Comment by raido** [comment] 2015-05-22 13:22
Please fix compatibility with ember-cli 0.2.5.

**Comment by glanzerd** [comment] 2015-05-23 15:51
I'll work on this today - sorry for the delay

**Comment by sglanzer** [comment] 2015-05-23 15:52
I'll work on this today - sorry for the delay

**Comment by sglanzer** [comment] 2015-05-24 03:49
We're actually respecting the autostart options, however blanket itself sets Qunit autostart to false, so we're respecting that...which means that the tests don't start...

Basically unless we can get an update to blanket that also respects the autostart options the only solution I can come up with is to go back to forcing autostart to true when the coverage is done loading.

For reference, in the blanket-require code when we first capture the autostart value, it's already false.
````
if (typeof(QUnit) === 'object') {
    var autostart = QUnit.config.autostart;
    window._$blanket_qunit = {
        autostart: autostart
    };
````

We store that value and restore it in our start.js code:
````
if (typeof(QUnit) === 'object') {
  QUnit.config.autostart = window._$blanket_qunit.autostart;
````

However, since it came in as false (via blanket) we're restoring false.

@jschilli @hjdivad any advice here?  I think we'll have to make the statement for now that we have to set qunit autostart to true.

**Comment by jschilli** [comment] 2015-05-24 09:59
I think that is a reasonable option to get us back in business. 

A more robust option would be for ember-qunit to add a callback mechanism for interested parties to get called prior to calling start. 

This would give us the opportunity to do the blanketing and not be responsible for starting qunit at all 



-jeff

**Comment by sglanzer** [comment] 2015-05-25 03:23
Released 0.5.2 to address this - the blanket-options now includes an autostart option (defaulting to true) to control the QUnit.config.autostart behavior after instrumentation is complete.  I've tested this in my projects, but I'd appreciate some additional confirmation before closing.

**Comment by givanse** [comment] 2015-05-25 04:44
Just upgraded, everything went well, thanks.

**Comment by raido** [comment] 2015-05-25 05:57
I have something weird going on:

```
QUnit.config.autostart = blanket.options('cliOptions').autostart !== false;
```

Line logs error: Cannot read property 'autostart' of undefined - i just installed ember-cli-blanket with "ember install ember-cli-blanket" command. I checked the version, it is 0.5.2.

I debugged this and ```blanket.options('cliOptions')``` is undefined.

Probably some not related to this issue.

**Comment by sglanzer** [comment] 2015-05-25 11:05
@raido Thanks, I'll look into it - I did test a fresh install, but I also ran ember generate ember-cli-blanket.  Anyhow, I'll probably just add a null check and default to true.

**Comment by raido** [comment] 2015-05-25 11:18
Fresh install worked fine for me too. But for my current project it fails. Null check does not fix it, then you would end up with moduleLoaderFinish is not defined error  in end of the test run.

**Comment by sglanzer** [comment] 2015-05-25 11:56
Thanks for the investigation - can you please raise this as a new issue so that we can track the solution separately?

**Comment by hjdivad** [comment] 2015-05-26 15:09
@sglanzer getting this fixed upstream seems like the right thing to do medium term.

For the short term, do you have an opportunity to read the user-value of `autostart` before blanket writes to it?

**Comment by ryanlabouve** [comment] 2015-09-15 19:12
Are we able to close this issue now? This has been resolved for me.

**Closed** 2016-03-04 14:06 UTC
